export enum ActivityCategory {
  HIKING = "HIKING",
  SPORTS = "SPORTS",
  MOVIES = "MOVIES",
  FESTIVALS = "FESTIVALS",
  PHOTOGRAPHY = "PHOTOGRAPHY",
  FOOD = "FOOD",
  MUSIC = "MUSIC",
  GAMING = "GAMING",
  CYCLING = "CYCLING",
  CAMPING = "CAMPING",
  TRAVEL = "TRAVEL",
  ART = "ART",
  WELLNESS = "WELLNESS",
  NIGHTLIFE = "NIGHTLIFE",
  OUTDOOR = "OUTDOOR",
  INDOOR = "INDOOR",
  OTHER = "OTHER",
}

export enum Mood {
  ADVENTUROUS = "ADVENTUROUS",
  RELAXED = "RELAXED",
  SOCIAL = "SOCIAL",
  CREATIVE = "CREATIVE",
  ACTIVE = "ACTIVE",
  ROMANTIC = "ROMANTIC",
  FAMILY = "FAMILY",
  SOLO = "SOLO",
}

export enum PriceLevel {
  FREE = "FREE",
  CHEAP = "CHEAP",
  MODERATE = "MODERATE",
  EXPENSIVE = "EXPENSIVE",
}
